## usage : v = RFVoltageAtTime(patternSet,t)
## patternSet : 1行目: 各電圧設定点の時間間隔
##              2行目: 設定電圧
## t: patternSet より、t での電圧を直線補間で求める。

function v = RFVoltageAtTime(patternSet,t)
  ## tLine : list of time, generated by function MagnetPattern

  ## setup RF Voltave pattern
#   patternSet=[0,25,10,50,514,50,50,427,50,824;
# 	   		0,0,180,400,400,400,20,20,400,400];
  ## make vList
  for n = 2:length(patternSet)
	patternSet(1,n) += patternSet(1,n-1);
  endfor
  v = interp1(patternSet(1,:),patternSet(2,:),t,'linear');
endfunction