1; #script file
## BM pattern of H+ 10MeV -> 200MeV
## bPattern=[0,35,60,85,599.2,624.2,649.2;
##	0.3662,0.3662,0.3761,0.4256,1.6473,1.6968,1.7067];
## require splinecomplete.m

#LOADPATH=['~/share/octave:' DEFAULT_LOADPATH];

function [bLine, tLine, bPoints_set] = MagnetPattern(tStep)
  ## capture period
  tPoints1 = [0,35]; #[msec]
  bPoints1 = [0.3662,0.3662]; #[T m]
  tLine1 = 25:tStep:35;
  bLine1 = interp1(tPoints1,bPoints1,tLine1,"linear");

  ## acceleration period
  tPoints3 = [85,599.2]; #[msec]
  bPoints3 = [0.4256,1.6473]; #[T m]
  bSlope = diff(bPoints3)/diff(tPoints3);
  tLine3 = 85:tStep:599.2;
  bLine3 = interp1(tPoints3,bPoints3,tLine3,"linear");

  ## initial acceleration period
  tPoints2 = [35,60,85]; #[msec]
  bPoints2 = [0.3662,0.3761,0.4256]; #[T m]
  tLine2 = 35:tStep:85;
  bLine2 = ppval(splinecomplete(tPoints2,bPoints2,[0,bSlope]),tLine2);

  ## end of acceleration period
  tPoints4 = [599.2,624.2,649.2]; #[msec]
  bPoints4 = [1.6473,1.6968,1.7067]; #[T m]
  tLine4 = 599.2:tStep:649.2;
  bLine4 = ppval(splinecomplete(tPoints4,bPoints4,[bSlope,0]),tLine4);

  tLine = [tLine1,tLine2,tLine3,tLine4];
  bLine = [bLine1,bLine2,bLine3,bLine4];

  bPoints_set = [[tPoints1,tPoints2,tPoints3,tPoints4];[bPoints1,bPoints2,bPoints3,bPoints4]]';

  #plotMagnetPattern(tLine1,bLine1,tLine2,bLine2,tLine3,bLine3,tLine4,bLine4);
endfunction

function plotMagnetPattern(tLine1,bLine1,tLine2,bLine2,tLine3,bLine3,tLine4,bLine4)
  tLine = [tLine1,tLine2,tLine3,tLine4];
  bLine = [bLine1,bLine2,bLine3,bLine4];
  plot(tLine1,bLine1,";capture period;",
	   tLine2,bLine2,";initial acceleration period;",
	   tLine3,bLine3,";acceleration period;",
	   tLine4,bLine4,";end of acceleration period;");
endfunction

function vList = voltagePattern(tLine)
  ## tLine : list of time, generated by function MagnetPattern

  ## setup RF Voltave pattern
  vPattern=[0,25,10,50,514,50,50,427,50,824;
	   		0,0,180,400,400,400,20,20,400,400];
  ## make vList
  for n = 2:length(vPattern)
	vPattern(1,n) += vPattern(1,n-1);
  endfor
  vList=interp1(vPattern(1,:),vPattern(2,:),tLine,'linear');
endfunction