## -*- texinfo -*-
## @deftypefn {Function File} {[@var{bclock_interp}, @var{bclock_interp} =} blpattern_with_bclock(@var{bclock_plus}, @var{bclock_minus}, @var{delta_b}, @var{bl_flatbase}, @var{periods}, @{t_step})
##
## Generate BL pattern by accumulating B-Clock and spilne interpolation. And make a plot.
## 
## @strong{Inputs}
## @table @var
## @item bclock_plus
## isf_data
## @item bclock_minus
## isf_data
## @item delta_b
## Magnetic field differnece per on B Clock in [T*m]
## @item bl_flatbase
## BL at the flat base.
## @item periods
## Timmings to switch B-Clock ON/OFF in seconds.
## @item t_step
## time interval for interpolation in seconds.
## @end table
## 
## @strong{Outputs}
## @table @var
## @item bl_interp
## BL pattern generated by interpolation.
## @item bclock_sum
## summation of @var{bclock_plus} and @var{bclock_minus}
## @end table
##
## @end deftypefn

##== History
## 2013-08-22
## * initial implementation

function varargout = blpattern_with_bclock(bclock_plus, bclock_minus,...
                                     delta_b, bl_flatbase, periods, t_step)
  ##== accumulate
  bclock_plus_accumulated = accumulate_bclock(bclock_plus, delta_b, bl_flatbase, periods);
  bclock_minus_accumulated = accumulate_bclock(bclock_minus, -1*delta_b, 0, periods(3:end));
  
  t_step = 10e-6; # データ間隔 10usec (100kHz)
  t_list = 0:t_step:2-t_step;
  ##== interplate
  [bclock_interp, bclock_sum] = interp_bclock(bclock_plus_accumulated, bclock_minus_accumulated,...
                                             periods, t_list);
  subplot(3,1,1);
  xyplot(bclock_interp);vline(periods);
  subplot(3,1,2);
  xyplot(bclock_interp, "-", bclock_sum, "-*");
  xlim([periods(1)-0.02, periods(1)+0.02]);
  ylim([bclock_interp(1,2)-0.0002, bclock_interp(1,2)+0.0002]);vline(periods);
  subplot(3,1,3);
  xyplot(bclock_interp, "-", bclock_sum, "-*");
  xlim([periods(2)-0.02, periods(2)+0.02]);
  ylim([max(bclock_interp(:,2))-0.0002, max(bclock_interp(:,2))+0.0002]);vline(periods);

   varargout = {bclock_interp, bclock_sum};
endfunction

%!test
%! blpattern_with_bclock(x)
