## -*- texinfo -*-
## @deftypefn {Function File} {@var{retval} =} rfvoltage_for_times(@var{pattern_set}, @var{t_values})
##
## @table @code
## @item @var{pattern_set}
## a matrix of @*
## [intervals of times of setting voltages;
##  setting voltages]
## @item @var{t_values}
## a list of times in msec.
## @end table
##
## @end deftypefn


## usage : retval = rfvoltage_for_times(pattern_set,t_values)
## pattern_set : 1行目: 各電圧設定点の時間間隔
##              2行目: 設定電圧
## t_values: pattern_set より、t_values での電圧を直線補間で求める。

##== History
## 2010-12-20
## * renamed from RFVoltageForTimes.

function retval = rfvoltage_for_times(pattern_set,t_values)
  ## t_values : list of time, generated by function MagnetPattern

  ## setup RF Voltave pattern
#   pattern_set=[0,25,10,50,514,50,50,427,50,824;
# 	   		0,0,180,400,400,400,20,20,400,400];
  ## make retval
  for n = 2:length(pattern_set)
	pattern_set(1,n) += pattern_set(1,n-1);
  endfor
  retval = interp1(pattern_set(1,:),pattern_set(2,:),t_values,"linear");
endfunction