%This sample file shows how to use wvfread with "logical data traces" as
%generated by the DL750:
filename= 'name_of_sample_file_without_extension';
[y_ch1,t] = wvfread(filename, 1, 1); % group1, trace1 in the sample file is AD-trace 
[y_logic,t] = wvfread(filename, 5, 1); % group5, trace1 in the sample file is logic trace

figure(1)
plot(t,y_ch1)

figure(2)
%use bitget to access the individual bits / digital channels of a logical signal (here: bits 1 and 16)
plot(t,bitget(y_logic,1),'b',t,bitget(y_logic,16), 'r') 
ylim([-0.1 1.1])